name: docker_api
description: Docker Engine API for Dart and Flutter
version: 0.0.1
homepage: https://github.com/luizeof/dart-docker-api

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.8
